name: Instrumentation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  instrumentation-test:

    runs-on: macOS-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: ${{ github.workspace }}/*/build/reports/
